export class AcademicRecords {
    constructor(
        public enrollDate: string,
        public status: string,
        public period: string,
        public modality: string,
        public studentType: string,
        public programId: string,
        public programDescription: string,
        public levelId: string,
        public levelDescription: string,
        public studyCauseId: string,
        public studyCauseDescription: string,
        public sessionCode: string,
        public sessionDescription: string,
        public csuId: string,
        public csuDescription: string,
        public officeId: string,
        public officeDescription: string,
        public pensumCode: string,
        public advance: string,
        public accountStatus: string,
        public accountDescription: string,
        public programStatus: string,
        public programStatusDescription: string,
        public lastPeriod: string,
        public graduationYear: string,
        public graduationDate: string,
        public universityCode: string,
        public stateCode: string,
        public advancePercentaje?: number,
        public approvedSubjects?: number,
        public disapprovedSubjects?: number,
        public institutionalAverage?: number,
        public transferAverage?: number,
        public generalAverage?: number,
        public graduationHonor?: number
    ) { }

}
